spring:

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/fitstat
    username: root
    password: root

server:
  port: 8080

jwt:
  clientId: fitstat-client-id
  client-secret: secret
  accessTokenValidititySeconds: 100
  refreshTokenValiditySeconds: 1000



