spring:


  jpa:
    hibernate:
      ddl-auto: validate

    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/fitstat
    username: root
    password: root
  main:
    banner-mode: off

server:
  port: 8081
