spring:

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/fitstat
    username: kanciapauser
    password: Kanciapauser123

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: fitstat-realm
  resource: login-app
  public-client: true

server:
  port: 8090




