spring:

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/fitstat
    username: root
    password: root

keycloak:
  realm: fitstat-realm
  resource: admin-fitstat
  auth-server-url: http://localhost:8080/auth
  credentials:
    secret: d61c8256-aed4-4faf-b17a-711904359eb4

server:
  port: 8090



